FROM centos:7.3.1611

COPY jdk1.8.0_144 /jdk1.8.0_144

COPY apache-maven-3.5.0 /apache-maven-3.5.0

COPY repository /root/.m2/repository

ENV JAVA_HOME=/jdk1.8.0_144

ENV MAVEN_HOME=/apache-maven-3.5.0

ENV PATH=$PATH:$JAVA_HOME/bin:$MAVEN_HOME/bin